language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
    allow_failures:
        - php: nightly

before_script:
    ## Init Composer
    - composer selfupdate --quiet
    - COMPOSER_ROOT_VERSION=dev-master composer install -n --dev

    ## Create temporary folders
    - mkdir -p build/logs

script:
    composer test

after_script:
    - php vendor/bin/coveralls -v

notifications:
    slack: locomotivemtl:d9h8ZWwTZ6b3WUsSP9s26nb1
    email: charcoal@locomotive.ca
